% a GUI for the recording answers of the recognition test
%
% Usage: mpsy_recognition_gui
%
% Copyright (C) 2007   Anika Baugart, Sven Franz
% Author :  Anika Baugart <anika.baugart AT stud.fh-oldenburg.de>,
%           Sven Franz <sven.franz AT stud.fh-oldenburg.de>
% Date   :  13 Nov 2007
% Based on the existing mpsy_*_gui psylab-scripts by Martin Hansen

%% This file is an extension for PSYLAB, a collection of scripts for
%% designing and controlling interactive psychoacoustical listening
%% experiments.  
%% This file is free software; you can redistribute it and/or modify
%% it under the terms of the GNU General Public License as published
%% by the Free Software Foundation; either version 2 of the License, 
%% or (at your option) any later version.  See the GNU General
%% Public License for more details:  http://www.gnu.org/licenses/gpl
%% This file is distributed in the hope that it will be useful,
%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

%% ===== the GUI for querying the user answer =====
%% The contents of the 'Tag'-property is a RESERVED WORD, DO NOT CHANGE!
psylab_gui = figure('Color', 0.1*round(10*rand(1,3)), ...
	'Position',[300 200 600 400], ...
	'Tag','psylab_answer_gui', ...
	'Name', ['recognition_gui -- PSYLAB V.' mpsy_version '  © M. Hansen, FH OOW'], ...
	'NumberTitle','off', ...
	'Toolbar','None', ...
	'Menubar','None');

% allow for keyboard presses as user-input 
% as an alternative for mouse-button-clicks 
set(psylab_gui, 'KeyPressFcn', 'M.RE = get(gcf, ''CurrentCharacter'');');

%% buttons for all possible answers/stimuli-names of recognition test
for count = 1 : M.N_RECOGNITION + M.COMPAREWITHNONE
    recognition_buttons(count) = uicontrol('Parent', psylab_gui, ...
	'Unit','normalized', ...
	'Callback',['M.RE= ''' num2str(count) ''';'], ...
	'Position',[0.1 0.35+count*((.95-0.35)/(M.N_RECOGNITION+M.COMPAREWITHNONE+1)) 0.8 (.95-0.35)/(M.N_RECOGNITION+M.COMPAREWITHNONE+1)], ...
	'String', sprintf('%d. %s', count, char(M.COMPRARE_NAMES(count))), ...
	'Tag','ButDOWN');
end

%% The contents of the 'Tag'-property is a RESERVED WORD, DO NOT CHANGE!
afc_fb = uicontrol('Parent', psylab_gui, ...
         'Unit','normalized', 'Position',[0.1 0.02 0.8 0.12], ...
         'Tag','psylab_feedback', ...
         'Style','text', ...
         'String','', ...
	 'FontSize', 14, 'ForegroundColor', 'red');

% an editable text field, e.g. for providing information to the user. 
%% The contents of the 'Tag'-property is a RESERVED WORD, DO NOT CHANGE!
afc_info = uicontrol('Parent', psylab_gui, ...
         'Unit','normalized', 'Position',[0.1 0.17 0.8 0.2], ...
         'Tag','psylab_info', ...
         'Style','text', ...
         'String','user answer possible via keyboard press', ...
         'KeyPressFcn', get(psylab_gui, 'KeyPressFcn'), ...
         'FontSize', 14, 'ForegroundColor', [0.4 0 0.2]);

%%% ============================================================
%%%  information about licenses, distribution, non-warranty
%%% ============================================================

psylab_about = uimenu('Parent', psylab_gui, ...
       'Label', 'About PSYLAB');
psylab_version = uimenu('Parent', psylab_about, ...
       'Label', 'PSYLAB Version', ...
       'Callback', 'mpsy_version;');
psylab_author = uimenu('Parent', psylab_about, ...
       'Label', 'View PSYLAB ABOUT in command window', ...
       'Callback', 'type PSYLAB-ABOUT');
psylab_distribution = uimenu('Parent', psylab_about, ...
       'Label', 'View PSYLAB DISTRIBUTION information in command window', ...
       'Callback', 'type DISTRIBUTION;');
psylab_nowarranty  = uimenu('Parent', psylab_about, ...
       'Label', 'View PSYLAB NON-WARRANTY in command window', ...
       'Callback', 'type NO-WARRANTY;');
psylab_license0 = uimenu('Parent', psylab_about, ...
       'Label', 'View LICENSES');
psylab_license  = uimenu('Parent', psylab_license0, ...
       'Label', 'View PSYLAB LICENSE', ...
       'Callback', 'type PSYLAB-LICENSE;');
psylab_gpl  = uimenu('Parent', psylab_license0, ...
       'Label', 'View GNU GENERAL PUBLIC LICENSE in command window', ...
       'Callback', 'type GNU-GPL;');

psylab_quitmenu = uimenu('Parent', psylab_gui, ...
       'Label', 'Quit');
psylab_quitrun = uimenu('Parent', psylab_quitmenu, ...
       'Label', 'quit only this run (r)', ...
       'Callback', 'M.RE=''r'';');
psylab_quitexp = uimenu('Parent', psylab_quitmenu, ...
       'Label', 'quit experiment (e)', ...
       'Callback', 'M.RE=''e'';');

% End of file:  mpsy_recognition_gui.m

% Local Variables:
% time-stamp-pattern: "40/Updated:  <%2d %3b %:y %02H:%02M, %u>"
% End:
